name: valorant_companion
description: A Flutter app for Valorant.

publish_to: 'none'

version: 1.1.2+3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  path_provider: ^2.0.9
  flutter_secure_storage: ^5.0.2
  video_player: ^2.3.0
  chewie: ^1.3.1
  sqflite_common_ffi: ^2.1.0+2
  window_manager: ^0.2.0
  sqflite: ^2.0.2
  firebase_core: ^1.14.0
  firebase_messaging: ^11.2.12
  overlay_support: ^1.2.1
  google_mobile_ads: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo_rounded.png
    - assets/images/valorant_logo.png
    - assets/images/featured.png
    - assets/images/store.png
    - assets/images/nightmarket.png
    - assets/images/inventory.png
    - assets/images/stats.png
    - assets/images/matches.png
    - assets/images/leaderboard.png
    - assets/images/crosshair.png
    - assets/images/valorantPoints.png
    - assets/images/radianitePoints.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
