// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbG8Wok2fpXzsfacJT2QF6caXyr6vOeFo',
    appId: '1:1027394381096:web:e4b5c395d515e196225c1d',
    messagingSenderId: '1027394381096',
    projectId: 'valorantcompanion-21017',
    authDomain: 'valorantcompanion-21017.firebaseapp.com',
    storageBucket: 'valorantcompanion-21017.appspot.com',
    measurementId: 'G-VT9JQ6Z3YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-jlRrM73MkXJu0yBay5QE_zcT2l8RSVA',
    appId: '1:1027394381096:android:c705e4acf5cf7e43225c1d',
    messagingSenderId: '1027394381096',
    projectId: 'valorantcompanion-21017',
    storageBucket: 'valorantcompanion-21017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoIe_V_jDgAV63247SqOMvNCYCcz0es0A',
    appId: '1:1027394381096:ios:f8da88d0e172ded1225c1d',
    messagingSenderId: '1027394381096',
    projectId: 'valorantcompanion-21017',
    storageBucket: 'valorantcompanion-21017.appspot.com',
    iosClientId: '1027394381096-2dtto3s2pagsb53nvj7st5331a3slt45.apps.googleusercontent.com',
    iosBundleId: 'np.com.ashutosh7.valocompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoIe_V_jDgAV63247SqOMvNCYCcz0es0A',
    appId: '1:1027394381096:ios:f8da88d0e172ded1225c1d',
    messagingSenderId: '1027394381096',
    projectId: 'valorantcompanion-21017',
    storageBucket: 'valorantcompanion-21017.appspot.com',
    iosClientId: '1027394381096-2dtto3s2pagsb53nvj7st5331a3slt45.apps.googleusercontent.com',
    iosBundleId: 'np.com.ashutosh7.valocompanion',
  );
}
